// Package mdtable reformats markdown tables so every column lines up.
//
// Tables copied from spreadsheets, hand-edited, or generated by tools tend
// to end up with inconsistent spacing, ragged rows, and misaligned pipes.
// Format walks a document, finds anything that looks like a GFM table, and
// rewrites just that block with evenly padded columns, leaving everything
// else in the document untouched.
package mdtable

import (
	"regexp"
	"strings"
	"unicode/utf8"
)

// Alignment is the column alignment declared by a table's separator row.
type Alignment int

const (
	AlignNone Alignment = iota
	AlignLeft
	AlignCenter
	AlignRight
)

var separatorCellRe = regexp.MustCompile(`^:?-+:?$`)

// Format scans input for markdown table blocks and rewrites each one with
// aligned columns and normalized spacing. Lines outside of a table block are
// passed through unchanged. Line endings in the output are always "\n".
func Format(input string) string {
	lines := strings.Split(strings.ReplaceAll(input, "\r\n", "\n"), "\n")
	out := make([]string, 0, len(lines))

	for i := 0; i < len(lines); {
		if looksLikeTableStart(lines, i) {
			end := i + 2
			for end < len(lines) && isTableRowLine(lines[end]) {
				end++
			}
			out = append(out, formatTable(lines[i:end])...)
			i = end
			continue
		}
		out = append(out, lines[i])
		i++
	}

	return strings.Join(out, "\n")
}

func looksLikeTableStart(lines []string, i int) bool {
	if i+1 >= len(lines) {
		return false
	}
	header := lines[i]
	if strings.TrimSpace(header) == "" || !strings.Contains(header, "|") {
		return false
	}
	return isSeparatorRow(splitCells(lines[i+1]))
}

func isTableRowLine(line string) bool {
	return strings.TrimSpace(line) != "" && strings.Contains(line, "|")
}

func isSeparatorRow(cells []string) bool {
	if len(cells) == 0 {
		return false
	}
	for _, c := range cells {
		if !separatorCellRe.MatchString(strings.TrimSpace(c)) {
			return false
		}
	}
	return true
}

func parseAlignment(cell string) Alignment {
	left := strings.HasPrefix(cell, ":")
	right := strings.HasSuffix(cell, ":")
	switch {
	case left && right:
		return AlignCenter
	case right:
		return AlignRight
	case left:
		return AlignLeft
	default:
		return AlignNone
	}
}

// splitCells splits a table row on unescaped "|" characters, unescaping
// "\|" into a literal pipe as it goes, and drops the optional leading and
// trailing empty cells produced by outer pipes.
func splitCells(row string) []string {
	trimmed := strings.TrimSpace(row)
	runes := []rune(trimmed)

	var cells []string
	var cur strings.Builder
	for i := 0; i < len(runes); i++ {
		switch {
		case runes[i] == '\\' && i+1 < len(runes) && runes[i+1] == '|':
			cur.WriteRune('|')
			i++
		case runes[i] == '|':
			cells = append(cells, strings.TrimSpace(cur.String()))
			cur.Reset()
		default:
			cur.WriteRune(runes[i])
		}
	}
	cells = append(cells, strings.TrimSpace(cur.String()))

	if len(cells) > 0 && cells[0] == "" && strings.HasPrefix(trimmed, "|") {
		cells = cells[1:]
	}
	if len(cells) > 0 && cells[len(cells)-1] == "" && strings.HasSuffix(trimmed, "|") {
		cells = cells[:len(cells)-1]
	}
	return cells
}

func padStrings(cells []string, n int) []string {
	if len(cells) >= n {
		return cells
	}
	padded := make([]string, n)
	copy(padded, cells)
	return padded
}

func padAligns(aligns []Alignment, n int) []Alignment {
	if len(aligns) >= n {
		return aligns
	}
	padded := make([]Alignment, n)
	copy(padded, aligns)
	return padded
}

// escapeCell re-escapes any literal pipe left in the cell content so the
// rendered row still parses as a table.
func escapeCell(cell string) string {
	return strings.ReplaceAll(cell, "|", `\|`)
}

func formatTable(block []string) []string {
	header := splitCells(block[0])
	aligns := make([]Alignment, 0, len(header))
	for _, c := range splitCells(block[1]) {
		aligns = append(aligns, parseAlignment(strings.TrimSpace(c)))
	}

	bodyRows := make([][]string, 0, len(block)-2)
	for _, line := range block[2:] {
		bodyRows = append(bodyRows, splitCells(line))
	}

	columns := len(header)
	if len(aligns) > columns {
		columns = len(aligns)
	}
	for _, row := range bodyRows {
		if len(row) > columns {
			columns = len(row)
		}
	}

	header = padStrings(header, columns)
	aligns = padAligns(aligns, columns)
	for i, row := range bodyRows {
		bodyRows[i] = padStrings(row, columns)
	}

	for i, c := range header {
		header[i] = escapeCell(c)
	}
	for _, row := range bodyRows {
		for i, c := range row {
			row[i] = escapeCell(c)
		}
	}

	widths := make([]int, columns)
	for i := range widths {
		widths[i] = 3 // minimum so "---" and ":-:" separators always fit
	}
	for i, c := range header {
		if w := utf8.RuneCountInString(c); w > widths[i] {
			widths[i] = w
		}
	}
	for _, row := range bodyRows {
		for i, c := range row {
			if w := utf8.RuneCountInString(c); w > widths[i] {
				widths[i] = w
			}
		}
	}

	out := make([]string, 0, len(bodyRows)+2)
	out = append(out, renderRow(header, widths, aligns))
	out = append(out, renderSeparator(widths, aligns))
	for _, row := range bodyRows {
		out = append(out, renderRow(row, widths, aligns))
	}
	return out
}

func renderRow(cells []string, widths []int, aligns []Alignment) string {
	parts := make([]string, len(cells))
	for i, c := range cells {
		parts[i] = padCell(c, widths[i], aligns[i])
	}
	return "| " + strings.Join(parts, " | ") + " |"
}

func renderSeparator(widths []int, aligns []Alignment) string {
	parts := make([]string, len(widths))
	for i, w := range widths {
		switch aligns[i] {
		case AlignLeft:
			parts[i] = ":" + strings.Repeat("-", w-1)
		case AlignRight:
			parts[i] = strings.Repeat("-", w-1) + ":"
		case AlignCenter:
			parts[i] = ":" + strings.Repeat("-", w-2) + ":"
		default:
			parts[i] = strings.Repeat("-", w)
		}
	}
	return "| " + strings.Join(parts, " | ") + " |"
}

func padCell(s string, width int, align Alignment) string {
	diff := width - utf8.RuneCountInString(s)
	if diff <= 0 {
		return s
	}
	switch align {
	case AlignRight:
		return strings.Repeat(" ", diff) + s
	case AlignCenter:
		left := diff / 2
		return strings.Repeat(" ", left) + s + strings.Repeat(" ", diff-left)
	default:
		return s + strings.Repeat(" ", diff)
	}
}
